name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH and Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        # Save the SSH key for GitHub Actions
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # SSH into EC2 and handle deployment
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd ~/trading-system
          
          # Pull the latest code from GitHub
          git pull git@github.com:sohammandal/trading-system.git main
          
          # 1) Docker Cleanup - Only Remove Unused Stuff
          docker container prune -f   # Remove stopped containers
          docker image prune -af      # Remove unused images
          docker volume prune -f      # Remove unused volumes
          docker network prune -f     # Remove unused networks

          # 2) OS-Level Cleanup
          journalctl --vacuum-size=100M
          sudo apt autoremove -y && sudo apt clean

          # 3) Stop & Remove Old Container
          docker stop trading-bot || true
          docker rm trading-bot || true

          # 4) Build & Run Fresh Container
          docker build -t trading-bot .
          docker run -d --restart unless-stopped --env-file .env --name trading-bot trading-bot
        EOF
        
        # Remove SSH key locally
        rm -f private_key.pem
